import { Metadata } from "next";
import "pretendard/dist/web/variable/pretendardvariable-dynamic-subset.css";
import { Toaster } from "sonner";
import "./globals.css";
import ReactQueryProvider from "@utils/provider";
import { AuthProvider } from "@context/AuthContext";

export const metadata: Metadata = {
  title: "team12-global-nomad",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <head>
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/icons/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/icons/favicon-16x16.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="120x120"
          href="/icons/apple-touch-icon.png"
        />
        <meta name="theme-color" content="#ffffff" />
      </head>
      <body className="min-w-96 antialiased">
        <AuthProvider>
          <ReactQueryProvider>
            <Toaster position="top-right" richColors />
            {children}
          </ReactQueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
